<a href="https://colab.research.google.com/github/hina81/Prog2kakushin/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import auth
from wordcloud import WordCloud
import gspread
from google.auth import default
import pandas as pd
import numpy as np
import datetime
import csv

import random

In [2]:
#csvファイル名を変更してください
df = pd.read_csv('希望シフト【期間を記入】  .csv')

In [4]:
#google formからの情報をNumPy配列に変換します
member = []
for me in df['お名前']:
  member.append(me)
#print(member)

mon = []
tue = []
wed = []
thu = []
fri = []
sat = []
sun = []

for sft in df['希望シフト']:
  if '月' in sft:
    mon.append(1)
  else:
    mon.append(0)

  if '火' in sft:
    tue.append(1)
  else:
    tue.append(0)

  if '水' in sft:
    wed.append(1)
  else:
    wed.append(0)

  if '木' in sft:
    thu.append(1)
  else:
    thu.append(0)

  if '金' in sft:
    fri.append(1)
  else:
    fri.append(0)

  if '土' in sft:
    sat.append(1)
  else:
    sat.append(0)


  if '日' in sft:
    sun.append(1)
  else:
    sun.append(0)

data = np.array([mon, tue, wed, thu, fri, sat, sun])
data_T = data.T

In [5]:
#行が人、列が曜日
print(data_T)

[[1 1 0 1 0 0 1]
 [0 1 1 0 0 0 0]
 [1 1 1 0 0 0 0]
 [0 1 1 0 1 1 0]
 [1 0 0 0 0 0 1]
 [0 1 0 0 1 0 0]
 [1 1 1 0 0 0 1]
 [0 0 0 0 1 1 1]
 [0 0 1 1 0 0 0]
 [1 0 0 1 0 1 0]
 [0 0 0 0 0 1 1]]


In [6]:
#各メンバーの合計勤務希望時間
kibou = np.sum(data_T, axis=0)
print(kibou)
#各曜日の合計希望数
zikan_sum = np.sum(data_T,axis=1)
print(zikan_sum)

[5 6 5 3 3 4 5]
[4 2 3 4 2 2 4 3 2 3 2]


In [8]:
week = ['月', '火', '水', '木', '金', '土', '日']

# メンバーごとに3つ以上の希望がある場合、ランダムに1つ削除する
while np.any(zikan_sum > 3):
    day_index = np.argmax(zikan_sum)
    member_index = np.argmax(kibou)
    data_T[day_index, member_index] = 0
    zikan_sum = np.sum(data_T, axis=0)
    kibou = np.sum(data_T, axis=1)

# 修正後
print("シフト:")
print(data_T)

KeyboardInterrupt: 